name: execute Kólga tests
runs:
  using: docker
  image: docker://${{ env.CONTAINER_REGISTRY_REPO }}:master-development
  args: [ "bash", "-c", "${{ inputs.command }}" ]
inputs:
  command:
    description: 'command to execute inside the Kólga container, in a bash shell'
    default: ''