name: execute Kólga tests
runs:
  using: docker
  image: docker://$CONTAINER_REGISTRY_REPO:master-development
  args: [ "bash", "-c", "${{ inputs.command }}" ]
inputs:
  command:
    description: 'command to execute inside the Kólga container, in a bash shell'
    default: ''