name: build

on: [push]

env:
  CONTAINER_REGISTRY: docker.anders.fi
  CONTAINER_REGISTRY_REPO: docker.anders.fi/devops/azure-kolga-demo
  CONTAINER_REGISTRY_USER: azure-registry-user
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
  DOCKER_IMAGE_NAME: kolga.github.riku

jobs:
  on_push:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to Docker container registry
        uses: docker/login-action@v1
        with:
          registry: docker.anders.fi
          username: azure-registry-user
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: pull Kólga Docker image
        run: docker pull docker.anders.fi/devops/azure-kolga-demo:master-development
      - name: build Kólga
        uses: ./.github/actions/build
      - name: all the tests
        uses: ./.github/actions/test
      - name: other tests
        run: |
          sudo chown $(whoami) /etc/hosts && echo 127.0.0.1 docker-registry >> /etc/hosts
          make test
        if: ${{ always() }}