name: build

on: [push]

env:
  CONTAINER_REGISTRY: docker.anders.fi
  CONTAINER_REGISTRY_REPO: docker.anders.fi/devops/azure-kolga-demo
  CONTAINER_REGISTRY_USER: azure-registry-user

jobs:
  login:
    runs-on: ubuntu-18.04
    steps:
      - name: login to Docker container registry
        uses: docker/login-action@v1
        with:
          registry: docker.anders.fi
          username: azure-registry-user
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          logout: false
      - name: pull Kólga Docker image
        run: docker pull docker.anders.fi/devops/azure-kolga-demo:master-development
  build:
    runs-on: ubuntu-18.04
    container: docker://docker.anders.fi/devops/azure-kolga-demo:master-development
    steps:
      - name: test action
        uses: ./.github/actions/test