name: build

on: [push]

env:
  CONTAINER_REGISTRY: docker.anders.fi
  CONTAINER_REGISTRY_REPO: docker.anders.fi/devops/azure-kolga-demo
  CONTAINER_REGISTRY_USER: azure-registry-user
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
  DOCKER_IMAGE_NAME: kolga.github.riku

jobs:
  on_push:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to Docker container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ env.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: pull Kólga Docker image
        run: docker pull $CONTAINER_REGISTRY_REPO:master-development
      - name: build Kólga
        run: docker run $CONTAINER_REGISTRY_REPO:master-development /bin/bash -c "./devops create_images && export BUILT_IMAGE=$(./devops docker_test_image) && echo "::set-env name=BUILT_DOCKER_TEST_IMAGE::$BUILT_IMAGE""
      - name: style tests
        run: |
          docker run $CONTAINER_REGISTRY_REPO:master-development /bin/bash -c "cat ./devops"
          docker run $CONTAINER_REGISTRY_REPO:master-development /bin/bash -c "make style-tests"
        if: ${{ always() }}
      - name: typing tests
        run: docker run $CONTAINER_REGISTRY_REPO:master-development /bin/bash -c "make typing-tests"
        if: ${{ always() }}
      - name: package tests
        run: docker run $CONTAINER_REGISTRY_REPO:master-development /bin/bash -c "make package-tests"
        if: ${{ always() }}
      - name: doc tests
        run: docker run $CONTAINER_REGISTRY_REPO:master-development /bin/bash -c "make docs"
        if: ${{ always() }}
      - name: functional tests
        run: |
          sudo chown $(whoami) /etc/hosts && echo 127.0.0.1 docker-registry >> /etc/hosts
          make test
        if: ${{ always() }}