name: build

on: [push]

env:
  CONTAINER_REGISTRY: docker.anders.fi
  CONTAINER_REGISTRY_REPO: docker.anders.fi/devops/azure-kolga-demo
  CONTAINER_REGISTRY_USER: azure-registry-user

jobs:
  login:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to Docker container registry
        uses: docker/login-action@v1
        with:
          registry: $CONTAINER_REGISTRY
          username: $CONTAINER_REGISTRY_USER
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          logout: false
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - name: Hello world
        run: export && echo "Hello, world!"